---
- name: "Setup local Fedora 35 system (user)"
  hosts: localhost
  connection: local
  tasks:
    - name: Add the flathub repository remote to the user installation
      flatpak_remote:
        name: flathub
        state: present
        flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
        method: user
    - name: Add the  repository remote to the user installation
      flatpak_remote:
        name: gnome-nightly
        state: present
        flatpakrepo_url: https://nightly.gnome.org/gnome-nightly.flatpakrepo
        method: user

    - name: Install flatpaks (flathub)
      community.general.flatpak:
        remote: flathub
        method: user
        name:
          - net.cozic.joplin_desktop
          - org.gnome.Extensions
          - com.github.tchx84.Flatseal
          - org.telegram.desktop
          - org.inkscape.Inkscape
          - org.shotcut.Shotcut
          - org.gimp.GIMP
          - com.github.rafostar.Clapper
          - com.discordapp.Discord
          - com.obsproject.Studio
          - org.audacityteam.Audacity
          - io.github.seadve.Kooha
          - com.spotify.Client
          - de.haeckerfelix.Shortwave
          - org.gnome.gitlab.somas.Apostrophe
          - com.github.johnfactotum.Foliate

    - name: Install flatpaks (gnome-nightly)
      community.general.flatpak:
        remote: gnome-nightly
        method: user
        name:
          - org.gnome.TextEditor.Devel
          - org.gnome.Builder

    - name: Disable Gnome software download update
      community.general.dconf:
        key: "/org/gnome/software/download-updates"
        value: "false"
        state: present
