- name: Setup local Fedora system for development
  hosts: localhost
  connection: local
  gather_facts: false
  vars_files:
    - vars/user_vars.yml
  tasks:
    - tags: superuser
      become: true
      block:
        - name: Add repository for vs code
          ansible.builtin.yum_repository:
            name: vscode
            file: vscode
            description: Visual Studio Code
            baseurl: https://packages.microsoft.com/yumrepos/vscode
            gpgkey: https://packages.microsoft.com/keys/microsoft.asc
            gpgcheck: true
          tags: [repo, vscode]
        - name: Install dev packages
          ansible.builtin.dnf5:
            name: "{{ dev_packages }}"
            state: present
          tags: packages
    - tags: user, git
      become: false
      block:
        - name: Setup git user
          community.general.git_config:
            name: user.name
            scope: global
            value: "{{ GIT_USERNAME }}"
        - name: Setup git email
          community.general.git_config:
            name: user.email
            scope: global
            value: "{{ GIT_EMAIL }}"
        - name: Setup git default branch
          community.general.git_config:
            name: init.defaultbranch
            scope: global
            value: main
        - name: Setup graph git alias
          community.general.git_config:
            name: alias.graph
            scope: global
            value: log --graph --abbrev-commit --date=relative --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(cyan)<%an>%Creset'
