- name: "Setup local Fedora system "
  hosts: localhost
  connection: local
  gather_facts: true
  vars_files:
    - vars/user_vars.yml
  ignore_errors: true
  tasks:
    - name: Set hostname
      tags: hostname
      become: true
      ansible.builtin.hostname:
        name: "{{ fedora_hostname }}"
        use: systemd
    - name: Setup repositories and install packages
      tags: packages
      become: true
      block:
        - name: Enable copr repositories
          tags: copr
          community.general.copr:
            state: enabled
            name: "{{ item }}"
          loop: "{{ copr_repositories }}"
        - name: Install rpm fusion repo
          ansible.builtin.dnf5:
            name:
              - https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ fedora_release }}.noarch.rpm
              - https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ fedora_release }}.noarch.rpm
            disable_gpg_check: true
            state: present
          ignore_errors: true
        - name: Install packages
          ansible.builtin.dnf5:
            name: "{{ dnf_packages }}"
            state: present
        - name: Install media codecs
          ansible.builtin.dnf5:
            name:
              - gstreamer1-plugins-bad-*
              - gstreamer1-plugins-good-*
              - gstreamer1-plugins-base
              - gstreamer1-plugin-openh264
              - gstreamer1-libav
            exclude: gstreamer1-plugins-bad-free-devel
            state: present
        - name: Remove unwanted packages
          ansible.builtin.dnf5:
            name:
              - PackageKit-command-not-found
              - PackageKit-gstreamer-plugin
            state: absent
    - name: Setup flatpak repo and install needed flatpaks
      tags: flatpak
      block:
        - name: Add the flathub repository remote to the user installation
          community.general.flatpak_remote:
            name: flathub
            state: present
            flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
            method: user
        - name: Install flatpaks (flathub)
          community.general.flatpak:
            remote: flathub
            method: user
            state: present
            name: "{{ flatpaks }}"
    - name: Configure gnome-software
      tags: gnome-software
      block:
        - name: Disable Gnome software download update
          community.general.dconf:
            key: /org/gnome/software/download-updates
            value: "false"
            state: present
        - name: Disable Gnome software update management
          community.general.dconf:
            key: /org/gnome/software/allow-updates
            value: "false"
            state: present
    - name: Setup .bashrc
      tags: bashrc
      block:
        - name: Add starship, zoxide, fzf and aliases to bashrc
          ansible.builtin.blockinfile:
            dest: ~/.bashrc
            block: |-
              eval "$(starship init bash)"
              eval "$(zoxide init bash)"
              eval "$(fzf --bash)"
              alias cd=z
              alias vi=nvim
              alias cat=bat
              alias lg=lazygit
              alias upd='cd ~/udv/github/dotfiles; git commit -a -m "update config"; git pull --rebase origin main; git push; cd -'
    - name: Setup OneDrive service
      tags: onedrive
      block:
        - name: Install onedrive
          ansible.builtin.dnf5:
            name: onedrive
            state: present
          become: true
        - name: Setup onedrive service
          ansible.builtin.systemd:
            name: onedrive
            scope: user
            enabled: true
            state: started
    - name: Setup configuration files from fedora-config repository
      tags: config_files
      block:
        - name: Checkout dotfiles git repo
          ansible.builtin.git:
            repo: git@github.com:timlau/dotfiles.git
            dest: "{{ config_dir }}"
            version: HEAD
        - name: Install starship config file
          ansible.builtin.file:
            src: "{{ config_dir }}/.config/starship.toml"
            dest: ~/.config/starship.toml
            state: link
            force: true
        - name: Install zed config files from dotfiles git repo
          ansible.builtin.file:
            src: "{{ config_dir }}/.config/zed"
            dest: ~/.config/zed
            state: link
            force: true
        - name: Install neovim config files from fedora-config git repo
          ansible.builtin.file:
            src: "{{ config_dir }}/.config/nvim"
            dest: ~/.config/nvim
            state: link
            force: true
        - name: Install tmux config file
          ansible.builtin.file:
            src: "{{ config_dir }}/.tmux.conf"
            dest: ~/.tmux.conf
            state: link
            force: true
        - name: Install ondrive sync_list config file
          ansible.builtin.file:
            src: "{{ config_dir }}/.config/onedrive/sync_list"
            dest: ~/.config/onedrive/sync_list
            state: link
            force: true
        - name: Install .fonts link
          ansible.builtin.file:
            src: ~/OneDrive/3.Resources/Content/Fonts
            dest: ~/.fonts
            state: link
            force: true
    - name: Setup aliases for fish shell
      tags: fish
      block:
        - name: Ensure fish configuration directory exists
          ansible.builtin.file:
            path: "{{ fish_config_dir }}/conf.d"
            state: directory
            mode: "0755"

        - name: Deploy custom fish aliases
          ansible.builtin.template:
            src: aliases.fish
            dest: "{{ fish_config_dir }}/conf.d/aliases.fish"
            owner: "{{ ansible_user_id }}"
            mode: "0644"

        - name: Ensure default shell is /bin/fish for "{{ ansible_user_id }}"
          ansible.builtin.user:
            name: "{{ ansible_user_id }}"
            shell: /bin/fish
          become: true

        - name: Install Fisher (if not already present)
          ansible.builtin.shell: |
            # Check if Fisher function exists
            if not type -q fisher
              # Install Fisher
              curl -sL https://raw.githubusercontent.com/jorgebucaran/fisher/main/functions/fisher.fish | source && fisher install jorgebucaran/fisher
              exit 1
            else
              echo "Fisher is already installed."
              exit 0
            end
          args:
            executable: /usr/bin/fish
            chdir: "{{ ansible_facts.user_dir }}"
          register: fisher_install_result
          changed_when: fisher_install_result.rc != 0

        - name: Deploy the complete fish_plugins file
          ansible.builtin.template:
            src: fish_plugins.j2
            dest: "{{ fish_plugins_file }}"
            owner: "{{ ansible_user_id }}"
            mode: "0644"

        - name: Run fisher update to install/sync plugins
          ansible.builtin.shell: |
            fish -c "fisher update"
          args:
            executable: /usr/bin/fish
            chdir: "{{ ansible_facts.user_dir }}"
